import { Upgrade, ContentType } from './types';

export const INITIAL_UPGRADES: Upgrade[] = [
  {
    id: 'camera_1',
    name: 'Веб-камера 720p',
    description: 'Лучшее качество — больше просмотров.',
    baseCost: 15,
    multiplier: 1.15,
    type: 'views',
    value: 1,
    level: 0,
    icon: 'Camera',
  },
  {
    id: 'mic_1',
    name: 'USB Микрофон',
    description: 'Чистый звук удерживает зрителей.',
    baseCost: 50,
    multiplier: 1.2,
    type: 'views',
    value: 5,
    level: 0,
    icon: 'Mic',
  },
  {
    id: 'lighting_1',
    name: 'Кольцевая лампа',
    description: 'Проф. вид привлекает подписчиков.',
    baseCost: 200,
    multiplier: 1.25,
    type: 'subscribers',
    value: 0.1,
    level: 0,
    icon: 'Sun',
  },
  {
    id: 'editor_1',
    name: 'Софт для монтажа',
    description: 'Лучшие склейки — выше вовлечение.',
    baseCost: 500,
    multiplier: 1.3,
    type: 'money',
    value: 2,
    level: 0,
    icon: 'Scissors',
  },
  {
    id: 'pc_1',
    name: 'Средний ПК',
    description: 'Быстрый рендер — больше контента.',
    baseCost: 1200,
    multiplier: 1.35,
    type: 'views',
    value: 25,
    level: 0,
    icon: 'Cpu',
  },
];

export const CONTENT_TYPES: ContentType[] = [
  {
    id: 'vlog',
    name: 'Дейли Влог',
    baseViews: 10,
    baseMoney: 0.5,
    duration: 5,
    unlockedAtSubs: 0,
  },
  {
    id: 'gaming',
    name: 'Летсплей',
    baseViews: 50,
    baseMoney: 2,
    duration: 15,
    unlockedAtSubs: 100,
  },
  {
    id: 'tech_review',
    name: 'Техно Обзор',
    baseViews: 200,
    baseMoney: 10,
    duration: 30,
    unlockedAtSubs: 1000,
  },
  {
    id: 'documentary',
    name: 'Видео Эссе',
    baseViews: 1000,
    baseMoney: 50,
    duration: 60,
    unlockedAtSubs: 10000,
  },
];
