import { Upgrade, ContentType } from './types';

export const INITIAL_UPGRADES: Upgrade[] = [
  {
    id: 'camera_1',
    name: 'Webcam 720p',
    description: 'Better resolution means more views.',
    baseCost: 15,
    multiplier: 1.15,
    type: 'views',
    value: 1,
    level: 0,
    icon: 'Camera',
  },
  {
    id: 'mic_1',
    name: 'USB Microphone',
    description: 'Clearer audio keeps people watching.',
    baseCost: 50,
    multiplier: 1.2,
    type: 'views',
    value: 5,
    level: 0,
    icon: 'Mic',
  },
  {
    id: 'lighting_1',
    name: 'Ring Light',
    description: 'Professional look attracts subscribers.',
    baseCost: 200,
    multiplier: 1.25,
    type: 'subscribers',
    value: 0.1,
    level: 0,
    icon: 'Sun',
  },
  {
    id: 'editor_1',
    name: 'Basic Editing Software',
    description: 'Better cuts mean more engagement.',
    baseCost: 500,
    multiplier: 1.3,
    type: 'money',
    value: 2,
    level: 0,
    icon: 'Scissors',
  },
  {
    id: 'pc_1',
    name: 'Mid-range PC',
    description: 'Faster rendering for more content.',
    baseCost: 1200,
    multiplier: 1.35,
    type: 'views',
    value: 25,
    level: 0,
    icon: 'Cpu',
  },
];

export const CONTENT_TYPES: ContentType[] = [
  {
    id: 'vlog',
    name: 'Daily Vlog',
    baseViews: 10,
    baseMoney: 0.5,
    duration: 5,
    unlockedAtSubs: 0,
  },
  {
    id: 'gaming',
    name: 'Gaming Let\'s Play',
    baseViews: 50,
    baseMoney: 2,
    duration: 15,
    unlockedAtSubs: 100,
  },
  {
    id: 'tech_review',
    name: 'Tech Review',
    baseViews: 200,
    baseMoney: 10,
    duration: 30,
    unlockedAtSubs: 1000,
  },
  {
    id: 'documentary',
    name: 'Video Essay',
    baseViews: 1000,
    baseMoney: 50,
    duration: 60,
    unlockedAtSubs: 10000,
  },
];
